### ISSUE TITLE
Nothing is displayed when I change the storage location

### ISSUE THREAD

**Issue by khanetor** [cockpit-project/cockpit-podman#1530]
I need to put my podman storage in a different location, specifically at `/var/lib/users/$USER/containers`. When I have done that, Podman is working normally, but nothing is visible in Cockpit Podman. I assume that Cockpit is only looking for Podman data in the default `$HOME/.local/containers` directory. If Cockpit can also parse the file `/etc/containers/storage.conf` to take into account the **graphroot** and **rootless_storage_path** keys, it can be more flexible.

**Comment by martinpitt** [comment]
c-podman doesn't parse any config files, it uses the [podman API](https://docs.podman.io/en/latest/_static/api.html). So that's where the bug is. For proper reproducing, what exactly did you do to move the storage location? I did that as well, with a ~/.local/share/containers → /cache/martin/containers symlink, which works fine. Obviously you did something else, I suppose some ~/.config/containers.storage.conf setting?

**Comment by khanetor** [comment]
> c-podman doesn't parse any config files, it uses the [podman API](https://docs.podman.io/en/latest/_static/api.html). So that's where the bug is. For proper reproducing, what exactly did you do to move the storage location? I did that as well, with a ~/.local/share/containers → /cache/martin/containers symlink, which works fine. Obviously you did something else, I suppose some ~/.config/containers.storage.conf setting?

Actually, I was wrong. When I restart my host, everything is visible again. We can close this.
