### ISSUE TITLE
Enable to remove image with more tags

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#172]
Image can have more tags. Deleting such image asks if we want to remove the image itself with all of its tags.
CLI users usually remove tags and when the last tag is removed the image itself is removed.
Maybe we should show images by their tags the same as `podman images` would show it and then this deleting would not be confusing?

@andreasn @garrett, WDYT?

**Comment by marusak** [comment]
hmm, I cannot make up my mind what would be the best option.
There are two options how we can list images:
1. By their ID (we do that now) - It is possible to delete image no matter how many tags it has. But it is not possible just to remove one tag. We could have button 'Delete tags' next to tags if there is more than one that would open dialog with list of all tags and would enable user to pick ones to delete.
2. By their name:tag - That would mean that if one image has more than one tag, it would be listed multiple times. It is what podman cli does. It makes it possible to delete one tag but not the whole image. I have feeling that deleting image is more important than deleting tag. (podman cli enables to delete by ID or name:tag)

@garrett WDYT?

**Comment by garrett** [comment]
Let's come up with a scenario and see if it makes sense.

I can imagine someone using tags and containers for several reasons — but the one that jumps out to me is the following scenario (user story time!):

Yvette wants to run the stable, production version of Nextcloud for corporate use, but has head of new features arriving in the next version. She wants to keep running the stable, but provide a beta version for testing, to make sure people are ready for it and so that corporate screenshots and documentation can be updated for the new release. Both versions will be installed simultaneously. Additionally, when the beta becomes stable, she would like to update, which means another tag.

This means there will be _at least_ 3 different Nextcloud images with different tags. She wouldn't want to delete the old stable and new stable when removing the beta. If everything works in the Beta, then upgrading to the final release would be a smooth transition, and she might actually want to delete both old images (beta and previous production).

From this (probably common) scenario, I'd suggest we do not delete all images, but provide a means of deleting multiple in a confirmation step.

What probably makes the most sense having a list of tags and preselect the tag from which the deletion action was started. The list should also show if the images are actively used for a container (or not), making the deletion step easier to understand.

If an image is selected that's associated with a container, a warning should show up, saying which container(s) are associated with the image, to make it really clear those would be deleted as well.

Perhaps something like this:

---

### Delete **Nextcloud** image

Multiple tags exist for the **Nextcloud** image. Select the tagged images to delete.

☐ 19.0.1
☑ 19-RC1
☐ 18.0.6 _used by 1 container_
☑ 17.0.7 _used by 3 containers_
      ⚠ **Warning** Deleting this tagged image will also delete containers: **NC-17-finance**, **NC-17-dev**, **NC-17-marketing**

[ **Delete tagged images** ]  Cancel 

---

@marusak: WDYT? :grin:

**Comment by garrett** [comment]
Mentioned in IRC:

Add a button to "select all" under the list; probably make it a link-styled button (similar to cancel). Only add it if there are ≥ 3 items.

(If there are two items, then you can "select all" by clicking the non-clicked item. There will always be one item in the list that is pre-selected, which corresponds to the image/tag entry where delete was originally clicked.)

**Comment by marusak** [comment]
> Perhaps something like this:

Like that! But there are things, that is not possible to do:
1) Used by n containers - We don't have this info. We know only sha of container. Nor does cli know this:
```
$ podman tag fedora:latest fedora:foo
$ podman run --name fromLatest fedora:latest
$ podman run --name fromFoo fedora:foo
$ podman ps -a
0c1adff1ae11  docker.io/library/fedora:32  /bin/bash  2 seconds ago  Exited (0) 2 seconds ago                                                  fromLatest
f095a8461c1d  docker.io/library/fedora:32  /bin/bash  2 seconds ago  Exited (0) 2 seconds ago                                                  fromFoo
```
2) Deleting this tagged image will also delete containers... - this is not how it works.
Continuing with the previous example:
```
$ podman rmi fedora:foo
Untagged: localhost/fedora:foo
$ podman ps -a
0c1adff1ae11  docker.io/library/fedora:32  /bin/bash  About a minute ago  Exited (0) About a minute ago                                                  fromLatest
f095a8461c1d  docker.io/library/fedora:32  /bin/bash  About a minute ago  Exited (0) About a minute ago                                                  fromFoo
```

Only when all tags would be removed, then it would delete associated containers, but we handle that already - directly with podman API, that it returns failure if it would need to remove some containers.

So other than that, the design looks good and I'll implement that. Thanks @garrett !

**Comment by garrett** [comment]
Ah cool. I wasn't sure. But I'm glad what I suggested _mainly_ applies and can be adapted. :+1: 

As containers aren't deleted when tagged images are deleted, knowing how many are used is not as critical, at least.

However, could we count up the # of hashes that match the given image? Then we know it's used by that certain number of containers?

**Comment by marusak** [comment]
> However, could we count up the # of hashes that match the given image? Then we know it's used by that certain number of containers?

sure, we already do this in 'Used by' so showing the number of containers is not a problem.
