### ISSUE TITLE
Explain that user service does not exist (when non-privileged log in)

### ISSUE THREAD

**Issue by therevoman** [cockpit-project/cockpit-podman#181]
Fresh install of RHEL 8, added brand new EPEL repo, cloned the master branch of the repo and started cockpit.   States PodMan service is not active.   but it is.

**Comment by marusak** [comment]
I suppose you see the `Podman Service is Not Active` page.
What happens when you click the `Start podman` button? Can you also please check logs in the browser?
When that does not start podman, can you please click on the `Troubleshoot` button and check logs of `io.podman.socket` (or navigate there directly through Services -> Sockets (tab on top) -> io.podman.socket.

I have had a similar problem after updating `podman`, since one needs to restart the socket when configuration changes. This is logged in the socket logs.

**Comment by williamjmorenor** [comment]
I think I hint the same issue in Fedora Rawhide as seen in #204

**Comment by marusak** [comment]
Good point @williamjmorenor !
@therevoman  do you login without privileges?
The page should be more friendly and notify user that they need privileges (now it only logs in browser logs). This is although out of score for Fedora, since soon we will support also user containers. Although this may be problem for RHEL 8 for much longer (not sure when we get cockpit-podman with user services there and also when podman-1.5.0 or higher gets into rhel-8).

I keep this as tracker of this problem.

**Comment by marusak** [comment]
We ship everywhere version with user containers. I think this is obsolete by now.
