### ISSUE TITLE
have to refresh

### ISSUE THREAD

**Issue by Raatty** [cockpit-project/cockpit-podman#374]
like a make a new container but it doesn't show up untill i refresh the page I don't think this is very ideal

**Comment by marusak** [comment]
Thank you for the report.
This is of course not the correct behaviour. Podman provided API was (is?) very unstable and was locking up very easily. There has been some updates that made these things better since podman 1.6 or so.

Can you please provide version that you are using?

Also please note that we are currently migrating to new podman API so hopefully it would make things better as well.

**Comment by Raatty** [comment]
# versions
fedora 32, podman 1.9.1, cockpit-podman 15
# expected behaviour
when i make a new container it should appear in ui without me needing to refresh page

**Comment by joequant** [comment]
I an using cockpit-podman 16 and podman dev release 2.0.0.  The UI isn't responding to external deletes of containers.

I can do coding so if someone suggests the possible problem, then I can help find.

**Comment by EricJeffrey** [comment]
really strange what I found, don't know if it is the problem of libpod or this project.
If I do `sudo service io.podman restart`, and click `start system podman service` which it will pop up on the web, and I can see response immediately  if I start, stop container or whatever, **no need to refresh**

system: `Ubuntu 18.04 lts`
browser:  `edge chromium, insecure https connection, ip:9090`
podman: 
```
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

Any ideads about this? @marusak 
Is it related to `events_logger` in `containers.conf` (podman config)?
or bug about varlink?

**Comment by Raatty** [comment]
seems to be fixed now?
