### ISSUE TITLE
[pod] Add container to a pod

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#487]
See https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/podman-pod-groups.png
https://github.com/cockpit-project/cockpit-podman/issues/238#issuecomment-662482073

**Comment by jelly** [comment]
Adding an existing [container to a pod](https://github.com/containers/podman/issues/3979) is not supported in podman so that's not something we can implement yet.

**Comment by garrett** [comment]
The action is to create a container inside the pod, not add an existing one. I guess the (old) pod mockup says "add container" instead of "create container".

The redesign mockup has "create" in the button and also includes pods:

![podman redesign](https://user-images.githubusercontent.com/10246/124738736-8694b080-df19-11eb-91e3-dae599569683.png)

**Comment by jelly** [comment]
The "Create container" modal changes the title to "Create container in $podname"
