### ISSUE TITLE
Mysterious image appears! (k8s.gcr.io/pause:3.2)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#598]
I never installed k8s.gcr.io/pause, but it's here on the page.

I'm guessing users would also be confused why weird images exist.

Should we handle it different from user-installed images? Probably.

**Comment by garrett** [comment]
Screenshot, last row in "Images":

![Uploading Screenshot_2020-11-17 Podman Containers - garrett Rain.png…]()

**Comment by marusak** [comment]
> I never installed k8s.gcr.io/pause, but it's here on the page.

it is base image for pods. When you create your first pod it is pulled. You can specify different base image, this is the default.

> Should we handle it different from user-installed images? Probably.

It still might be user-installed. And we actually cannot be sure that it was pulled just as dep or which image was pulled this way. `podman images` lists it and I think we want to stay in sync with this command otherwise we are going to confuse users "why output of podman is different than in cockpit".
