### ISSUE TITLE
Huge gap between container's title and body content

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#710]
There's an enormous gap between the heading of containers and its body content (the list):

![Screenshot_2021-04-19 Podman containers - garrett Rain(2)](https://user-images.githubusercontent.com/10246/115249337-c7ee9e80-a128-11eb-9d99-8eeec600bdf9.png)

Images doesn't have this issue.

**Comment by marusak** [comment]
This is due to using `<Toolbar>` PF4 component.
We use it in Cockpit and we have local overwrites as https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/terminal.scss#L69 and https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/ct-card.scss#L68

I am looking into this if we can just import it.

**Comment by marusak** [comment]
Aha, we are actually already importing it, just `.ct-card` class is never being defined.

**Comment by marusak** [comment]
Ok, so we need new lib version. It gets a bit better but still not as we want it. It is due to what components we use for showing containers. Right now I am thinking that I don't want to go and fix this up and rather wait for the new design that @garrett is working on. If the design does not change this container items then I would fix it up anyway.

**Comment by garrett** [comment]
The redesign will probably take some time to fix. I would suggest updating the libraries and then add a quick hack to reduce the spacing in the meantime, and then remove the hack when the redesign lands.

**Comment by marusak** [comment]
The gap is smaller now. Is it still too big @garrett ?

![Screenshot from 2021-10-05 11-43-43stilltoobig](https://user-images.githubusercontent.com/12330670/135999874-a1297cd3-dc2e-4847-8322-4627492032c8.png)

**Comment by garrett** [comment]
> The gap is smaller now. Is it still too big?

Yes, still too big of a gap.

It should be more like this (not pixel perfect; rough estimate):

![image](https://user-images.githubusercontent.com/10246/136046671-29494d06-0f77-41ec-8b1c-fc60b1f78c66.png)

**Comment by jelly** [comment]
One issue is [margin top](https://github.com/cockpit-project/cockpit-podman/blob/main/src/Containers.scss#L2) set on container-section for I think seperating pods. The other issue is that `pf-card__body` having a padding of 24px.
