### ISSUE TITLE
Containers "show" filter dropdown icon overlaps with "Only running"

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-podman#755]
![image](https://user-images.githubusercontent.com/67428/132473684-61c10f04-e001-447b-8a8b-cab0725305fe.png)

**Comment by garrett** [comment]
It seems like this is how PF does selects? :thinking: 

If I look at the select here in Firefox...

![Screen Shot 2021-09-15 at 14 35 46](https://user-images.githubusercontent.com/10246/133434387-141229e9-f0ba-4ba9-8270-064043ce4515.png)

(It's slightly different from your screenshot, with a few pixels of space.)

I see that there's not enough padding around the arrow:

![image](https://user-images.githubusercontent.com/10246/133432678-f4518f4f-b6de-4567-9700-80ec6db641d1.png)

It says there's 24px to the right, which is 16*1.5, which is PF's `lg`:
![image](https://user-images.githubusercontent.com/10246/133432835-da2763cb-998d-4c98-9f25-bcb26a0c48a2.png)

And if I change the padding on the widget like thus (done live in Firefox):
```scss
select.pf-c-form-control {
 --pf-c-form-control__select--PaddingRight: var(--pf-global--spacer--xl);
}
```

Then I get something more appropriate:

![Screen Shot 2021-09-15 at 14 32 02](https://user-images.githubusercontent.com/10246/133433829-4c808c63-ce6b-4627-9548-8eb2bdc30eb1.png)

![image](https://user-images.githubusercontent.com/10246/133433909-61ec4b7d-d519-4a9f-9088-7420441357db.png)

So that's looking purely at Cockpit. What about PatternFly?

Same thing:

If I go to https://www.patternfly.org/v4/components/form-select and look at the first example, then change the width to "auto" instead of 100% and change the string so it's the longest one in the dropdown, I get this:

![image](https://user-images.githubusercontent.com/10246/133434083-8c98dbed-0f84-4021-9120-4184c90b80e2.png)

**Comment by garrett** [comment]
Most of the time, PatternFly has options that are stretched to a certain width (often, but not always 100%). 

It's also probably worth noting that the main PatternFly devs usually use a Mac, often with Chrome.  Fonts will render differently on macOS than Linux, and fonts render a bit differently in Safari, Chrome, and Firefox, which might influence things a little too.

But, I think this is mainly related to PF forms not being used in auto widths. I think this might be an upstream issue. I also wonder how much of a difference there is between a widgety select versus an HTML-based form... this could influence things here as well.

**Comment by garrett** [comment]
I've opened an upstream issue.

It looks like this is a local fix, at least here on Firefox:

```scss
select.pf-c-form-control {
    /* left padding + icon width + right padding */
    --pf-c-form-control--PaddingRight: 37px;
    --pf-c-form-control--PaddingLeft: 7px;
}
```

I'm looking to see if these are the same values that fix it for other browsers too, and if we can use something other than `px` (like some calculation with spacer).

**Comment by garrett** [comment]
WebKit and Blink both need 4px more on the right @ 41px, oddly.

**Comment by garrett** [comment]
## Chrome
![select-chromium](https://user-images.githubusercontent.com/10246/134156724-ed08d3b8-0eb2-47d3-ba0d-d4c28b0ffcca.png)
## GNOME Web
![select-webkit](https://user-images.githubusercontent.com/10246/134156727-745edbf4-27b3-448d-828c-968fde0dec03.png)
## Firefox
![select-firefox](https://user-images.githubusercontent.com/10246/134156730-548f3795-de5b-4b1a-83c7-244f6232026d.png)

---

It looks like Firefox has some internal padding around the text, causing the difference.

**Comment by garrett** [comment]
I've pushed a fix to `patternfly-4-overrides.scss` in https://github.com/cockpit-project/cockpit/pull/16376. It would need to be imported here once it lands.
